/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Usuario
 */
public class JFEmpleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFUsuario
     */
    public JFEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jXPanel3 = new org.jdesktop.swingx.JXPanel();
        labelMover = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        jXPanel4 = new org.jdesktop.swingx.JXPanel();
        btnMinimizar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        txtDocumento = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        comboTipoDocumento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtApellido1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtApellido2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jfcCargo = new com.nextic.filtercomponent.components.JFilterComponent2();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtCargo = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtAreaDeTrabajo = new javax.swing.JTextField();
        jfcAreaDeTrabajo = new com.nextic.filtercomponent.components.JFilterComponent2();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setIconifiable(true);

        jXPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jXPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 184, 280, 10));

        txtNombre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtNombre.setBorder(null);
        txtNombre.setMargin(new java.awt.Insets(10, 2, 0, 2));
        txtNombre.setName("Nombre"); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jXPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 280, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel1.setText("Nombre");
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jXPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 127, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel2.setText("Documento");
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jXPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 127, -1, -1));
        jXPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 187, 280, 10));

        jXPanel3.setBackground(new java.awt.Color(52, 133, 254));
        jXPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jXPanel3.add(labelMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 36));

        labelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        labelTitulo.setFont(new java.awt.Font("Calibri Light", 0, 30)); // NOI18N
        labelTitulo.setText("EMPLEADO");
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jXPanel3.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 240, 40));

        jXPanel4.setBackground(new java.awt.Color(52, 133, 254));
        jXPanel4.setLayout(new javax.swing.BoxLayout(jXPanel4, javax.swing.BoxLayout.LINE_AXIS));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materialDesign/ic_minm_white_24px.png"))); // NOI18N
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.setFocusable(false);
        btnMinimizar.setMaximumSize(new java.awt.Dimension(40, 33));
        btnMinimizar.setMinimumSize(new java.awt.Dimension(40, 33));
        btnMinimizar.setPreferredSize(new java.awt.Dimension(40, 33));
        btnMinimizar.setRequestFocusEnabled(false);
        btnMinimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materialDesign/ic_minm_white_24px_rollover.png"))); // NOI18N
        jXPanel4.add(btnMinimizar);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materialDesign/ic_close_white_24px.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setFocusable(false);
        btnCerrar.setMaximumSize(new java.awt.Dimension(40, 33));
        btnCerrar.setMinimumSize(new java.awt.Dimension(40, 33));
        btnCerrar.setPreferredSize(new java.awt.Dimension(40, 33));
        btnCerrar.setRequestFocusEnabled(false);
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materialDesign/ic_close_white_24px_rollover.png"))); // NOI18N
        jXPanel4.add(btnCerrar);

        jXPanel3.add(jXPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 4, 80, 30));

        jXPanel1.add(jXPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 90));

        txtDocumento.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtDocumento.setBorder(null);
        txtDocumento.setMargin(new java.awt.Insets(10, 2, 0, 2));
        txtDocumento.setName("Documento"); // NOI18N
        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });
        jXPanel1.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 163, 170, -1));

        btnGuardar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diskette6472.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setForeground(new java.awt.Color(102, 102, 102));
        btnGuardar.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btnGuardar.setMaximumSize(new java.awt.Dimension(85, 33));
        btnGuardar.setMinimumSize(new java.awt.Dimension(85, 33));
        btnGuardar.setPreferredSize(new java.awt.Dimension(85, 33));
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diskette72rollover.png"))); // NOI18N
        jXPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 100, 80));

        comboTipoDocumento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "CE" }));
        comboTipoDocumento.setFocusCycleRoot(true);
        comboTipoDocumento.setForeground(new java.awt.Color(102, 102, 102));
        comboTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoDocumentoActionPerformed(evt);
            }
        });
        jXPanel1.add(comboTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 156, 47, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("TD");
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jXPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 127, 39, -1));
        jXPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 470, 130, 10));

        txtApellido1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtApellido1.setBorder(null);
        txtApellido1.setMargin(new java.awt.Insets(10, 2, 0, 2));
        txtApellido1.setName("Primer Apellido"); // NOI18N
        txtApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido1ActionPerformed(evt);
            }
        });
        jXPanel1.add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 266, 280, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel4.setText("Primer apellido");
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jXPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 230, -1, -1));
        jXPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 280, 10));

        txtApellido2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtApellido2.setBorder(null);
        txtApellido2.setMargin(new java.awt.Insets(10, 2, 0, 2));
        txtApellido2.setName("Segundo Apellido"); // NOI18N
        txtApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido2ActionPerformed(evt);
            }
        });
        jXPanel1.add(txtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 266, 280, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Segundo apellido");
        jXPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));
        jXPanel1.add(jfcCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 353, 150, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel6.setText("Cargo");
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jXPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 310, -1, 30));
        jXPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 384, 460, 10));

        txtCargo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtCargo.setBorder(null);
        txtCargo.setMargin(new java.awt.Insets(10, 2, 0, 2));
        txtCargo.setName("usuario"); // NOI18N
        txtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoActionPerformed(evt);
            }
        });
        jXPanel1.add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 460, -1));
        jXPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 460, 10));

        txtAreaDeTrabajo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtAreaDeTrabajo.setBorder(null);
        txtAreaDeTrabajo.setMargin(new java.awt.Insets(10, 2, 0, 2));
        txtAreaDeTrabajo.setName("usuario"); // NOI18N
        txtAreaDeTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaDeTrabajoActionPerformed(evt);
            }
        });
        jXPanel1.add(txtAreaDeTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 446, 460, -1));
        jXPanel1.add(jfcAreaDeTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 439, 150, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel7.setText("Área de trrabajo");
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jXPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 408, -1, 20));
        jXPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 290, 280, 10));
        jXPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 384, 130, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void comboTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoDocumentoActionPerformed

    private void txtApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido1ActionPerformed

    private void txtApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido2ActionPerformed

    private void txtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoActionPerformed

    private void txtAreaDeTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaDeTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaDeTrabajoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnMinimizar;
    public javax.swing.JComboBox<String> comboTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel3;
    private org.jdesktop.swingx.JXPanel jXPanel4;
    public com.nextic.filtercomponent.components.JFilterComponent2 jfcAreaDeTrabajo;
    public com.nextic.filtercomponent.components.JFilterComponent2 jfcCargo;
    public javax.swing.JLabel labelMover;
    private javax.swing.JLabel labelTitulo;
    public javax.swing.JTextField txtApellido1;
    public javax.swing.JTextField txtApellido2;
    public javax.swing.JTextField txtAreaDeTrabajo;
    public javax.swing.JTextField txtCargo;
    public javax.swing.JTextField txtDocumento;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
