
package vista;
/**
 *
 * @author Yonatan
 */




/**
 *
 * @author Yonatan
 */
public class JFPrincipalOrden extends javax.swing.JFrame {

    /**
     * Creates new form JF_Principal
     */
   
    public JFPrincipalOrden() {
        initComponents();
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        panelMenu = new org.jdesktop.swingx.JXPanel();
        panelMenuCargo = new org.jdesktop.swingx.JXPanel();
        btnCargo = new javax.swing.JButton();
        panelMenuArea = new org.jdesktop.swingx.JXPanel();
        btnAreaDeTrabajo = new javax.swing.JButton();
        panelMenuListaOrdenes = new org.jdesktop.swingx.JXPanel();
        btnListaOrdenes = new javax.swing.JButton();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXPanel3 = new org.jdesktop.swingx.JXPanel();
        jXPanel4 = new org.jdesktop.swingx.JXPanel();
        btnMinimizar = new javax.swing.JButton();
        btnMaximizar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        labelMover = new javax.swing.JLabel();
        jXPanel5 = new org.jdesktop.swingx.JXPanel();
        txtApellido1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtNombreCompleto = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        panelScroll = new javax.swing.JScrollPane();
        panelRestaurantes = new javax.swing.JPanel();
        txtDocumento = new javax.swing.JTextField();
        txtDocumento1 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();

        popupMenu.setBackground(new java.awt.Color(51, 204, 255));
        popupMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        popupMenu.setBorderPainted(false);

        panelMenu.setBackground(new java.awt.Color(51, 204, 255));
        panelMenu.setPaintBorderInsets(false);
        panelMenu.setLayout(new java.awt.GridLayout(3, 1));

        panelMenuCargo.setBackground(new java.awt.Color(52, 133, 254));

        btnCargo.setBackground(new java.awt.Color(52, 133, 254));
        btnCargo.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/id.png"))); // NOI18N
        btnCargo.setText("Cargo");
        btnCargo.setBorder(null);
        btnCargo.setContentAreaFilled(false);
        btnCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCargo.setForeground(new java.awt.Color(255, 255, 255));
        btnCargo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCargo.setIconTextGap(15);
        btnCargo.setMargin(new java.awt.Insets(2, 20, 2, 14));
        btnCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuCargoLayout = new javax.swing.GroupLayout(panelMenuCargo);
        panelMenuCargo.setLayout(panelMenuCargoLayout);
        panelMenuCargoLayout.setHorizontalGroup(
            panelMenuCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuCargoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
        );
        panelMenuCargoLayout.setVerticalGroup(
            panelMenuCargoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuCargoLayout.createSequentialGroup()
                .addComponent(btnCargo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelMenu.add(panelMenuCargo);

        panelMenuArea.setBackground(new java.awt.Color(52, 133, 254));

        btnAreaDeTrabajo.setBackground(new java.awt.Color(255, 255, 255));
        btnAreaDeTrabajo.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnAreaDeTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/factory.png"))); // NOI18N
        btnAreaDeTrabajo.setText("Área de trabajo");
        btnAreaDeTrabajo.setBorder(null);
        btnAreaDeTrabajo.setBorderPainted(false);
        btnAreaDeTrabajo.setContentAreaFilled(false);
        btnAreaDeTrabajo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAreaDeTrabajo.setFocusPainted(false);
        btnAreaDeTrabajo.setForeground(new java.awt.Color(255, 255, 255));
        btnAreaDeTrabajo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAreaDeTrabajo.setIconTextGap(15);
        btnAreaDeTrabajo.setMargin(new java.awt.Insets(2, 14, 2, 25));
        btnAreaDeTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaDeTrabajoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuAreaLayout = new javax.swing.GroupLayout(panelMenuArea);
        panelMenuArea.setLayout(panelMenuAreaLayout);
        panelMenuAreaLayout.setHorizontalGroup(
            panelMenuAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAreaDeTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
        );
        panelMenuAreaLayout.setVerticalGroup(
            panelMenuAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuAreaLayout.createSequentialGroup()
                .addComponent(btnAreaDeTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelMenu.add(panelMenuArea);

        panelMenuListaOrdenes.setBackground(new java.awt.Color(52, 133, 254));

        btnListaOrdenes.setBackground(new java.awt.Color(255, 255, 255));
        btnListaOrdenes.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnListaOrdenes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/orden32.png"))); // NOI18N
        btnListaOrdenes.setText("Listado de ordenes");
        btnListaOrdenes.setBorder(null);
        btnListaOrdenes.setBorderPainted(false);
        btnListaOrdenes.setContentAreaFilled(false);
        btnListaOrdenes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListaOrdenes.setFocusPainted(false);
        btnListaOrdenes.setForeground(new java.awt.Color(255, 255, 255));
        btnListaOrdenes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnListaOrdenes.setIconTextGap(15);
        btnListaOrdenes.setMargin(new java.awt.Insets(2, 14, 2, 25));
        btnListaOrdenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaOrdenesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuListaOrdenesLayout = new javax.swing.GroupLayout(panelMenuListaOrdenes);
        panelMenuListaOrdenes.setLayout(panelMenuListaOrdenesLayout);
        panelMenuListaOrdenesLayout.setHorizontalGroup(
            panelMenuListaOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuListaOrdenesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnListaOrdenes, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
        );
        panelMenuListaOrdenesLayout.setVerticalGroup(
            panelMenuListaOrdenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuListaOrdenesLayout.createSequentialGroup()
                .addComponent(btnListaOrdenes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelMenu.add(panelMenuListaOrdenes);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(52, 133, 254));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jXPanel1.setBackground(new java.awt.Color(52, 133, 254));
        jXPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 226, 226)));
        jXPanel1.setLayout(new javax.swing.BoxLayout(jXPanel1, javax.swing.BoxLayout.Y_AXIS));

        jXPanel3.setBackground(new java.awt.Color(52, 133, 254));

        jXPanel4.setBackground(new java.awt.Color(52, 133, 254));
        jXPanel4.setLayout(new javax.swing.BoxLayout(jXPanel4, javax.swing.BoxLayout.LINE_AXIS));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materialDesign/ic_minm_white_24px.png"))); // NOI18N
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.setFocusable(false);
        btnMinimizar.setMaximumSize(new java.awt.Dimension(40, 33));
        btnMinimizar.setMinimumSize(new java.awt.Dimension(40, 33));
        btnMinimizar.setPreferredSize(new java.awt.Dimension(40, 33));
        btnMinimizar.setRequestFocusEnabled(false);
        btnMinimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materialDesign/ic_minm_white_24px_rollover.png"))); // NOI18N
        jXPanel4.add(btnMinimizar);

        btnMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materialDesign/ic_check_box_outline_blank_white_24px.png"))); // NOI18N
        btnMaximizar.setBorderPainted(false);
        btnMaximizar.setContentAreaFilled(false);
        btnMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMaximizar.setFocusable(false);
        btnMaximizar.setMaximumSize(new java.awt.Dimension(40, 33));
        btnMaximizar.setMinimumSize(new java.awt.Dimension(40, 33));
        btnMaximizar.setPreferredSize(new java.awt.Dimension(40, 33));
        btnMaximizar.setRequestFocusEnabled(false);
        btnMaximizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materialDesign/ic_check_box_outline_blank_white_24px_rollover.png"))); // NOI18N
        jXPanel4.add(btnMaximizar);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materialDesign/ic_close_white_24px.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setFocusable(false);
        btnCerrar.setMaximumSize(new java.awt.Dimension(40, 33));
        btnCerrar.setMinimumSize(new java.awt.Dimension(40, 33));
        btnCerrar.setPreferredSize(new java.awt.Dimension(40, 33));
        btnCerrar.setRequestFocusEnabled(false);
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materialDesign/ic_close_white_24px_rollover.png"))); // NOI18N
        jXPanel4.add(btnCerrar);

        labelMover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        jXPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jXPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApellido1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtApellido1.setBorder(null);
        txtApellido1.setMargin(new java.awt.Insets(10, 2, 0, 2));
        txtApellido1.setName("Primer Apellido"); // NOI18N
        txtApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido1ActionPerformed(evt);
            }
        });
        jXPanel5.add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 139, 40, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel4.setText("TD");
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jXPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 30, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel5.setText("Nombre completo");
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jXPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 150, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel6.setText("Documento");
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jXPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 100, -1, 30));
        jXPanel5.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 171, 410, 10));

        txtNombreCompleto.setEditable(false);
        txtNombreCompleto.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreCompleto.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtNombreCompleto.setBorder(null);
        txtNombreCompleto.setMargin(new java.awt.Insets(10, 2, 0, 2));
        txtNombreCompleto.setName("usuario"); // NOI18N
        txtNombreCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCompletoActionPerformed(evt);
            }
        });
        jXPanel5.add(txtNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 139, 410, 30));
        jXPanel5.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 171, 40, 10));
        jXPanel5.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 171, 160, 10));

        panelScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelRestaurantes.setBackground(new java.awt.Color(248, 248, 248));
        panelRestaurantes.setLayout(null);
        panelScroll.setViewportView(panelRestaurantes);

        jXPanel5.add(panelScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 880, 330));

        txtDocumento.setEditable(false);
        txtDocumento.setBackground(new java.awt.Color(255, 255, 255));
        txtDocumento.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtDocumento.setBorder(null);
        txtDocumento.setMargin(new java.awt.Insets(10, 2, 0, 2));
        txtDocumento.setName("usuario"); // NOI18N
        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });
        jXPanel5.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 139, 160, 30));

        txtDocumento1.setEditable(false);
        txtDocumento1.setBackground(new java.awt.Color(255, 255, 255));
        txtDocumento1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtDocumento1.setBorder(null);
        txtDocumento1.setMargin(new java.awt.Insets(10, 2, 0, 2));
        txtDocumento1.setName("usuario"); // NOI18N
        txtDocumento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumento1ActionPerformed(evt);
            }
        });
        jXPanel5.add(txtDocumento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 49, 220, 30));
        jXPanel5.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 81, 220, 10));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Código de empleado");
        jXPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 10, -1, 30));

        labelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        labelTitulo.setFont(new java.awt.Font("Calibri Light", 0, 30)); // NOI18N
        labelTitulo.setText("GENERAR ORDEN");
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jXPanel3Layout = new javax.swing.GroupLayout(jXPanel3);
        jXPanel3.setLayout(jXPanel3Layout);
        jXPanel3Layout.setHorizontalGroup(
            jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel3Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(labelMover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jXPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
            .addGroup(jXPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jXPanel3Layout.setVerticalGroup(
            jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel3Layout.createSequentialGroup()
                .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMover, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jXPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        jXPanel1.add(jXPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//         Model2.cerra_conexion_JPA();
    }//GEN-LAST:event_formWindowClosed

    private void btnCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargoActionPerformed

    private void btnAreaDeTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaDeTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAreaDeTrabajoActionPerformed

    private void btnListaOrdenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaOrdenesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaOrdenesActionPerformed

    private void txtApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido1ActionPerformed

    private void txtNombreCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCompletoActionPerformed

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void txtDocumento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumento1ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAreaDeTrabajo;
    public javax.swing.JButton btnCargo;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnListaOrdenes;
    public javax.swing.JButton btnMaximizar;
    public javax.swing.JButton btnMinimizar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel3;
    private org.jdesktop.swingx.JXPanel jXPanel4;
    public org.jdesktop.swingx.JXPanel jXPanel5;
    public javax.swing.JLabel labelMover;
    private javax.swing.JLabel labelTitulo;
    public org.jdesktop.swingx.JXPanel panelMenu;
    public org.jdesktop.swingx.JXPanel panelMenuArea;
    public org.jdesktop.swingx.JXPanel panelMenuCargo;
    public org.jdesktop.swingx.JXPanel panelMenuListaOrdenes;
    public javax.swing.JPanel panelRestaurantes;
    public javax.swing.JScrollPane panelScroll;
    public javax.swing.JPopupMenu popupMenu;
    public javax.swing.JTextField txtApellido1;
    public javax.swing.JTextField txtDocumento;
    public javax.swing.JTextField txtDocumento1;
    public javax.swing.JTextField txtNombreCompleto;
    // End of variables declaration//GEN-END:variables

}
