/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Usuario
 */
public class JFUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFUsuario
     */
    public JFUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtConfirmarContraseña = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jXPanel3 = new org.jdesktop.swingx.JXPanel();
        labelMover = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        jXPanel4 = new org.jdesktop.swingx.JXPanel();
        btnMinimizar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setIconifiable(true);

        jXPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jXPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jXPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 162, 355, 10));

        btnGuardar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diskette6472.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setForeground(new java.awt.Color(102, 102, 102));
        btnGuardar.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btnGuardar.setMaximumSize(new java.awt.Dimension(85, 33));
        btnGuardar.setMinimumSize(new java.awt.Dimension(85, 33));
        btnGuardar.setPreferredSize(new java.awt.Dimension(85, 33));
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/diskette72rollover.png"))); // NOI18N
        jXPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 100, 80));

        txtUsuario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtUsuario.setBorder(null);
        txtUsuario.setMargin(new java.awt.Insets(10, 2, 0, 2));
        txtUsuario.setName("usuario"); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jXPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 138, 355, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel1.setText("Usuario");
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jXPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 105, -1, 20));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel2.setText("Contraseña");
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jXPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 187, -1, 20));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Tipo");
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jXPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 351, 96, -1));

        txtContraseña.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtContraseña.setBorder(null);
        txtContraseña.setName("contraseña"); // NOI18N
        jXPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 223, 355, -1));

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "LIMITADO" }));
        comboTipo.setFocusCycleRoot(true);
        comboTipo.setForeground(new java.awt.Color(102, 102, 102));
        jXPanel1.add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 374, 203, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jLabel4.setText("Confirmar contraseña");
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jXPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 275, -1, 18));

        txtConfirmarContraseña.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txtConfirmarContraseña.setBorder(null);
        txtConfirmarContraseña.setName("confirmación de contraseña"); // NOI18N
        jXPanel1.add(txtConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 311, 355, -1));
        jXPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 247, 355, 10));
        jXPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 335, 355, 10));
        jXPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 410, 355, 10));

        jXPanel3.setBackground(new java.awt.Color(52, 133, 254));
        jXPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelMover.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jXPanel3.add(labelMover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 36));

        labelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        labelTitulo.setFont(new java.awt.Font("Calibri Light", 0, 30)); // NOI18N
        labelTitulo.setText("USUARIO DEL SISTEMA");
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jXPanel3.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 290, 40));

        jXPanel4.setBackground(new java.awt.Color(52, 133, 254));
        jXPanel4.setLayout(new javax.swing.BoxLayout(jXPanel4, javax.swing.BoxLayout.LINE_AXIS));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materialDesign/ic_minm_white_24px.png"))); // NOI18N
        btnMinimizar.setBorderPainted(false);
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimizar.setFocusable(false);
        btnMinimizar.setMaximumSize(new java.awt.Dimension(40, 33));
        btnMinimizar.setMinimumSize(new java.awt.Dimension(40, 33));
        btnMinimizar.setPreferredSize(new java.awt.Dimension(40, 33));
        btnMinimizar.setRequestFocusEnabled(false);
        btnMinimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materialDesign/ic_minm_white_24px_rollover.png"))); // NOI18N
        jXPanel4.add(btnMinimizar);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materialDesign/ic_close_white_24px.png"))); // NOI18N
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setFocusable(false);
        btnCerrar.setMaximumSize(new java.awt.Dimension(40, 33));
        btnCerrar.setMinimumSize(new java.awt.Dimension(40, 33));
        btnCerrar.setPreferredSize(new java.awt.Dimension(40, 33));
        btnCerrar.setRequestFocusEnabled(false);
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materialDesign/ic_close_white_24px_rollover.png"))); // NOI18N
        jXPanel4.add(btnCerrar);

        jXPanel3.add(jXPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 4, 90, 30));

        jXPanel1.add(jXPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnMinimizar;
    public javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel3;
    private org.jdesktop.swingx.JXPanel jXPanel4;
    public javax.swing.JLabel labelMover;
    private javax.swing.JLabel labelTitulo;
    public javax.swing.JPasswordField txtConfirmarContraseña;
    public javax.swing.JPasswordField txtContraseña;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
